CREATE TABLE gifchat_conversations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    conversation_location TEXT NOT NULL,
    -- Although this is a chronological identifier, 
    -- we are choosing to store it as BIGINT because
    -- we're going to do comparison of ms since epoch.
    -- 42 as default to give us a value to ID unused
    -- rooms by.
    last_connection BIGINT DEFAULT 42 NOT NULL,
    messages TEXT[] default ARRAY[]::text[] NOT NULL
);