CREATE TABLE gifchat_conversations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    conversation_location TEXT NOT NULL,
    last_connection TIMESTAMP DEFAULT now() NOT NULL,
    messages TEXT[] default ARRAY[]::text[] NOT NULL
);